package com.saucelabs.mobile.utils;

import com.saucelabs.mobile.config.ConfigReader;
import io.appium.java_client.AppiumDriver;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.Capabilities;

import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.TreeMap;
import java.util.concurrent.ConcurrentSkipListSet;

/**
 * Fills the Allure "Environment" panel from the LIVE session (what the test actually ran on),
 * not from config. Every distinct device of the run is listed, so parallel runs stay traceable.
 */
public final class AllureEnvironmentWriter {

    private static final Logger LOG = LogManager.getLogger(AllureEnvironmentWriter.class);
    private static final Set<String> DEVICES = new ConcurrentSkipListSet<>();
    private static final Map<String, String> RUN_INFO = new TreeMap<>();

    private AllureEnvironmentWriter() {
    }

    public static synchronized void record(AppiumDriver driver) {
        Capabilities caps = driver.getCapabilities();
        String device = cap(caps, "deviceManufacturer") + " " + cap(caps, "deviceModel")
                + " (" + cap(caps, "platformName") + " " + cap(caps, "platformVersion")
                + ", " + cap(caps, "deviceUDID", "udid") + ")";
        boolean newDevice = DEVICES.add(device);
        if (!newDevice && !RUN_INFO.isEmpty()) {
            return;   // nothing new to write
        }
        RUN_INFO.put("Platform", ConfigReader.platform().name());
        RUN_INFO.put("Execution.Env", ConfigReader.env());
        RUN_INFO.put("Appium.Server", ConfigReader.get("appium.server.url"));
        RUN_INFO.put("App", appName(ConfigReader.get("app.path")));
        RUN_INFO.put("Automation", cap(caps, "automationName"));
        RUN_INFO.put("Tags", System.getProperty("cucumber.filter.tags", "all"));
        RUN_INFO.put("Java", System.getProperty("java.version"));
        RUN_INFO.put("Devices", String.join(" | ", DEVICES));
        write();
    }

    private static void write() {
        Path dir = Path.of(System.getProperty("allure.results.directory", "target/allure-results"));
        Properties props = new Properties();
        props.putAll(RUN_INFO);
        try {
            Files.createDirectories(dir);
            try (Writer out = Files.newBufferedWriter(dir.resolve("environment.properties"))) {
                props.store(out, "Generated by AllureEnvironmentWriter");
            }
        } catch (IOException e) {
            LOG.warn("Allure environment not written: {}", e.getMessage());
        }
    }

    /** File name for local paths; cloud ids (bs://...) kept as-is - Path.of("bs://x") throws on Windows. */
    private static String appName(String app) {
        if (app.contains("://")) {
            return app;
        }
        return Path.of(app).getFileName().toString();
    }

    /** Session caps may come back with or without the "appium:" vendor prefix. */
    private static String cap(Capabilities caps, String... names) {
        for (String name : names) {
            for (String key : new String[]{name, "appium:" + name}) {
                Object value = caps.getCapability(key);
                if (value != null && !value.toString().isBlank()) {
                    return value.toString();
                }
            }
        }
        return "?";
    }
}
